export const APPLICATIONS_UI = {
  TITLE: 'Application Management',
  SUBTITLE: 'Review and manage internship applications from both students and universities.',
  SEARCH_PLACEHOLDER: 'Search student name, student ID, email...',
  INCLUDE_TERMINAL: 'Include Terminal:',
  ALL_PHASES: 'All Internship Phases',
  ALL_STATUSES: 'All Statuses',
  ALL_POSITIONS: 'All Positions',
  ALL_SCHOOLS: 'All Schools',
  ALL_AUDIENCES: 'All Audiences',
  PERIOD_PLACEHOLDER: 'Month — Year',
  EMPTY_STATE: 'No applications found.',
  JOB_CLOSED: 'Closed',
  JOB_DELETED: 'Deleted',
  TABS: {
    SELF_APPLY: 'Self-apply',
    UNI_ASSIGN: 'Uni Assign',
  },
  MODAL_TITLE: {
    REJECT_UNI: 'Reject University Assignment',
    REJECT_STANDARD: 'Reject Application',
  },
  COLUMNS: {
    STUDENT_NAME: 'Student Name',
    STUDENT_ID: 'Student ID',
    SCHOOL: 'School',
    JOB_APPLIED: 'Job Applied',
    APPLIED_DATE: 'Applied Date',
    STATUS: 'Status',
    ACTIONS: 'Actions',
    STUDENT_AND_SCHOOL: 'Student & School',
    REQUESTED_POSITION: 'Requested Position',
    REQUESTED_DATE: 'Requested Date',
  },
  MESSAGES: {
    REJECT_REASON_REQUIRED: 'Please provide a reason for rejection.',
    REJECT_REASON_PLACEHOLDER: 'Enter reason here...',
    REJECT_CONFIRM: 'Confirm Rejection',
    REJECT_CANCEL: 'Cancel',
  },
  MODAL: {
    DETAIL_TITLE: 'Application Detail',
    CANDIDATE_PROFILE: 'Candidate Profile',
    BASIC_INFO: 'Basic Information',
    STUDENT_ID: 'Student ID',
    EMAIL: 'Email',
    PHONE: 'Phone',
    UNIVERSITY: 'University',
    APPLYING_FOR: 'Applying For',
    JOB_POSITION: 'Job Position',
    INTERN_PHASE: 'Intern Phase',
    AUDIENCE: 'Audience',
    STATUS_TIMELINE: 'Status Timeline',
    DEPARTMENT: 'Department:',
    VIEW_CV: 'View Portfolio / CV',
    CLOSE: 'Close',
    UNSPECIFIED: 'Not specified',
    GENERAL_APP: 'General Application',
    SOURCE: 'Source',
    UNI_ASSIGN: 'Uni-Assign',
    SELF_APPLY: 'Self-Apply',
    CLOSED: 'Closed',
    DELETED: 'Deleted',
    MOVE_TO_INTERVIEWING: 'Move to Interviewing',
    SEND_OFFER: 'Send Offer',
    MARK_PLACED: 'Mark as Placed',
    APPROVE_ASSIGNMENT: 'Approve Assignment',
    REJECT: 'Reject',
  },
  COMMON: {
    LOADING: '...',
    EMPTY: '—',
    DATE_FORMAT: 'DD MMM, YYYY',
  },
  BULLET: '•',
};
