export const UI_TEXT = {
  COMMON: {
    LOADING: 'Loading...',
    UPLOAD: 'Upload',
    CANCEL: 'Cancel',
    APPLY: 'Apply',
    SAVE: 'Save',
    EDIT: 'Edit',
    DELETE: 'Delete',
    CONFIRM: 'Confirm',
    SUCCESS: 'Success',
    ERROR: 'Error',
    SEARCH: 'Search...',
    FILTER: 'Filter',
    TODAY: 'Today',
    TRY_AGAIN: 'Try Again',
    TOTAL_RECORDS: 'Total records:',
    PAGE: 'page',
    PAGE_SUFFIX: '/page',
    SCORE_DENOMINATOR: '/ 10',
    SLASH: '/',
    ASTERISK: '*',
    DASH: '-',
    OPEN_PAREN: '(',
    CLOSE_PAREN: ')',
    QUESTION: '?',
    UNAUTHORIZED: 'Unauthorized',
    UNAUTHORIZED_DESC: 'You do not have permission to access this page.',
    BACK_TO_LOGIN: 'Back to login',
    NOT_PROVIDED: 'Not provided',
    VAT: 'Tax Code/VAT',
    INFO_ICON: '(i)',
    UNIT_ID_REQUIRED: 'UnitId (required for selected role)',
    UNIT_ID_OPTIONAL: 'UnitId (optional)',
    RETRY: 'Retry',
    MINUS: '-',
    DOUBLE_MINUS: '--',
    TRIPLE_ASTERISK: '***',
    ACTION: 'Action',
    PHASE_VAL: 'phase.',
    DELETE_SUCCESS: 'Object deleted successfully',
    UPDATE_SUCCESS: 'Updated successfully',
    CREATE_SUCCESS: 'Created successfully',
    DELETE_CONFIRM: 'Confirm Deletion',
    ARE_YOU_SURE: 'Are you absolutely sure?',
    DOT: '·',
    EM_DASH: '—',
    TOTAL: 'Total records',
    VERIFY_SESSION: 'Verifying secure session...',
  },
  USER_MANAGEMENT: {
    TITLE: 'User Management',
    STUDENT_TITLE: 'Student Management',
    STAFF_TITLE: 'Staff Management',
    SUBTITLE: 'Manage accounts and their roles across the hierarchy.',
    CREATE_TITLE: 'Create User',
    EDIT_TITLE: 'Edit User',
    DELETE_TITLE: 'Delete User',
    DELETE_CONFIRM: 'Are you sure you want to delete this user?',
    RESET_PWD_TITLE: 'Reset Password',
    RESET_PWD_CONFIRM: 'Are you sure you want to reset password for this user?',
    ADD: 'Add User',
    CREATE_DESCRIPTION: 'Create a new user account.',
    FULL_NAME: 'Full Name',
    EMAIL_ADDRESS: 'Email Address',
    ASSIGNED_ROLE: 'Assigned Role',
    PHONE_NUMBER: 'Phone Number',
    UNIT: 'Unit',
    CODE: 'Code',
    USER: 'User',
    ROLE: 'Role',
    STATUS: 'Status',
    CREATE_BTN: 'Create',
    CANCEL: 'Cancel',
    NO_DATA: 'No data found',
    SEARCH_PLACEHOLDER: 'Search name/email/code',
    NO: 'No',
    S_FOUND: 's found',
    FILTER_ROLE: 'Filter role',
    FILTER_STATUS: 'Filter status',
    MANAGE_ADMIN_ACCOUNTS: 'Manage accounts across the system',
    DELETE_HINT: 'This action cannot be undone.',
    CONFIRM_DELETE: 'Confirm delete',
    LOSS_ACCESS_HINT: 'User will lose access to the system.',
    RESET_PASSWORD: 'Reset Password',
    ACCOUNT_SECURITY: 'Account Security & Password Reset',
    TARGET: 'Target',
    REASON: 'Reason',
    REASON_PLACEHOLDER: 'Reason (10..500 chars)',
    UPDATE_PROFILE: 'Update Profile',
    UPDATE_INFO: 'Update information for this account.',
    FULL_NAME_LABEL: 'Full name',
    PHONE_OPTIONAL: 'Phone (optional)',
    GENDER: 'Gender',
    MALE: 'Male',
    FEMALE: 'Female',
    OTHER: 'Other',
    DOB_LABEL: 'Date of birth (YYYY-MM-DD)',
    AVATAR_LABEL: 'Avatar URL (optional)',
    CLASS_LABEL: 'Student class (optional)',
    MAJOR_LABEL: 'Student major (optional)',
    GPA_LABEL: 'Student GPA (optional)',
    SAVE_CHANGES: 'Save Changes',
    NOT_FOUND: 'Users not found',
    UNIT_SELECTION_HINT:
      'Unit selection datasource is not available in FE code yet. Enter a UnitId GUID if required.',
    ADMIN_USERS_CAP: 'Users',
    CREATE_CAP: 'Create',
    DELETE_CAP: 'Delete',
    DELETE_BTN: 'Delete',
    FULL_NAME_PLACEHOLDER: 'Enter full name',
    EMAIL_PLACEHOLDER: 'Enter email address',
    PHONE_PLACEHOLDER: 'Enter phone number',
    NO_UNIT_FOUND: 'No unit found',
    SELECT_A: 'Select a',
    S_FOUND_SUFFIX: 's found',
    LOADING_DOTS: 'Loading...',
    ERR_FULL_NAME_REQ: 'Please enter a full name.',
    ERR_EMAIL_REQ: 'Please enter an email address.',
    ERR_INVALID_EMAIL: 'Please enter a valid email format (e.g., user@example.com).',
    ERR_CREATE_FAILED: 'Failed to create user. Please check your inputs and try again.',
    SUCCESS_CREATED: 'Successfully created',
    NOT_MATCHING_CRITERIA: "We couldn't find any users matching your criteria.",
    REASON_SHORT: 'Reason too short (min 10 chars)',
    RESET_SUCCESS: 'Password reset email sent successfully',
    RESET_FAILED: 'Failed to reset password',
    RESET_SUBTITLE: 'Account Security & Credential Recovery',
    TARGET_ACCOUNT: 'Target Account',
    REASON_DESCRIPTION: 'Please provide a brief justification for this reset action...',
    REASON_HINT: 'Min. 10 characters required for security audit trails.',
    DELETE_IRREVERSIBLE: 'Irreversible action. Account access will be permanently revoked.',
    CONFIRM_ACCOUNT_DELETE: 'Confirm Account Deletion',
    CONFIRM_DELETE_TEXT: 'I understand this action is permanent and cannot be reversed.',
    ERR_LOAD_FAILED: 'Failed to load user data',
    ERR_UPDATE_FAILED: 'Update failed',
    SUCCESS_UPDATED: 'User information updated successfully',
    ERR_DOB_FORMAT: 'Date of birth must be in YYYY-MM-DD format',
    ERR_GPA_NUMBER: 'Student GPA must be a number',
    INTERNSHIP_TERM_LABEL: 'Internship Term',
    TERM_PLACEHOLDER_LOADING: 'Loading terms...',
    TERM_PLACEHOLDER_SELECT: 'Select internship term',
    TERM_PLACEHOLDER_NONE: 'No terms available',
  },
  ENTERPRISES: {
    TITLE: 'Enterprise Ecosystem',
    SUBTITLE:
      'Strategically manage corporate partners, tax identities, and industrial classifications.',
    SEARCH_PLACEHOLDER: 'Search by enterprise name, code, or tax ID...',
    ADD: 'Add Enterprise',
    NOT_FOUND: 'No enterprises found',
    ONBOARD: 'Onboard Enterprise',
    BRAND_LOGO: 'Brand Logo',
    COVER_IMAGE: 'Cover Image',
    NAME: 'Enterprise Name',
    TAX_ID_LONG: 'Tax Identification Number',
    TAX_ID_SHORT: 'Tax ID',
    INDUSTRY: 'Industry Section',
    DESC: 'Company Description',
    ADDRESS: 'Headquarters Address',
    WEBSITE: 'Corporate Website',
    ENTERPRISE: 'Enterprise',
    INDUSTRY_COLUMN: 'Industry',
    WEBSITE_TITLE: 'Open Website',
    WEBSITE_DESCRIPTION: 'Official Page',
    EDIT_TITLE: 'Edit Profile',
    EDIT_DESCRIPTION: 'Update Information',
    DELETE_TITLE: 'Delete',
    DELETE_DESCRIPTION: 'Irreversible Action',
    REMOVE_SUCCESS: 'Successfully removed partner',
    CONTACT_EMAIL: 'Contact Email',
    EMAIL_PLACEHOLDER: 'e.g. contact@enterprise.com',
    INVALID_EMAIL: 'Please enter a valid email address',
    INITIALIZE: 'Initialize Enterprise',
    DELETE_SUBTITLE: 'Remove enterprise account',
    INDUSTRY_PREFIX: 'Industry',
  },
  UNIVERSITIES: {
    TITLE: 'University Management',
    DESCRIPTION: 'Manage educational institutions, their codes, and headquarters information.',
    SEARCH_PLACEHOLDER: 'Search by university name or code...',
    CREATE: 'Create University',
    UPDATE: 'Update University',
    NAME: 'University Name',
    CODE: 'University Code',
    ADDRESS: 'Address',
    UNIVERSITY: 'University',
    UPDATE_DESC: 'Update institution profile',
    IRREVERSIBLE: 'Irreversible action',
    DELETE_HINT:
      'This action will permanently remove the institution from the system. This cannot be undone.',
    DELETE_SURE: 'Are you absolutely sure?',
    DELETE_WARN_PREFIX: 'You are about to delete ',
    LOGO_LABEL: 'Institution Logo',
    IDENTITY: 'University Identity',
    NAME_PLACEHOLDER: 'Official University Name',
    CODE_PLACEHOLDER: 'EX: VNU-H',
    ADDRESS_PLACEHOLDER: 'Headquarters Address',
    NOT_FOUND: 'No universities found',
    CODE_PREFIX: 'Code',
    NAME_REQUIRED: 'University name is required',
    CODE_REQUIRED: 'University code is required',
    ADDRESS_REQUIRED: 'Address is required',
    CONTACT_EMAIL: 'Contact Email',
    EMAIL_PLACEHOLDER: 'e.g. contact@university.edu.vn',
    ERR_INVALID_EMAIL: 'Invalid email format',
  },
  ENROLLMENT: {
    STUDENT_IN_PHASE: 'This student is currently in the',
    PHASE_HINT:
      'phase. Business details and evaluations will be updated as the internship progresses.',
    IMPORT_TITLE: 'Import Student List',
    IMPORT_SUBTITLE: 'Upload student list to enroll them',
    DOWNLOAD_TEMPLATE: 'Download template',
    DRAG_HINT: 'Drag file here or click to upload (.xls, .xlsx)',
    FILE_SIZE_ERROR: (size) => `File must be < ${size}MB`,
    VALID: 'VALID',
    INVALID: 'INVALID',
    ERROR: 'ERROR',
    TOOLTIP_VALID: 'Valid',
    COLUMNS: {
      FULL_NAME: 'Full Name',
      STUDENT_ID: 'Student ID',
      EMAIL: 'Email',
      VALIDITY: 'Validity',
    },
  },
  USER_PROFILE: {
    VIEW_LINK: 'View Link',
    SKILL_NAME: 'Name',
  },
  BUTTON: {
    CLOSE: 'Close',
    SAVE_CHANGES: 'Save Changes',
    CREATE: 'Create',
    CANCEL: 'Cancel',
    TRY_AGAIN: 'Try Again',
    APPLY: 'Apply',
    DELETE: 'Delete',
  },
  TIPTAP: {
    PLACEHOLDER: 'Enter description...',
    PROMPT_URL: 'Enter URL',
    IMAGE_ONLY: 'Please select a valid image file',
    IMAGE_TOO_LARGE: 'Image is too large. Please select an image smaller than 3MB',
  },
  ROLES: {
    SUPER_ADMIN: 'Super Admin',
    UNI_ADMIN: 'University Admin',
    ORG_ADMIN: 'Organization Admin',
  },
  UPLOADER: {
    EDIT_AVATAR: 'Edit avatar',
    UPDATE_COVER: 'Update Cover Photo',
    UPLOAD_BANNER: 'Upload Cover Banner',
    RATIO_NOTE: 'Recommended ratio 4.5:1',
    LOGO: 'LOGO',
  },
  PAGINATION: {
    TOTAL: 'Total records:',
    PAGE_5: '5/page',
    PAGE_10: '10/page',
    PAGE_20: '20/page',
    PAGE_50: '50/page',
  },
  BACKLOG: {
    INCLUDED_IN_SPRINT: 'will be included in this sprint',
    ISSUE: 'issue',
    ISSUES: 'issues',
    ASTERISK_SPACE: ' *',
    UNKNOWN_EPIC: 'Unknown Epic',
  },
  ENTERPRISE: {
    DASHBOARD_TITLE: 'Enterprise Dashboard',
    DASHBOARD_WELCOME: 'Welcome to the Enterprise Dashboard. Select an option from the sidebar.',
  },
  ERROR: {
    COMMUNICATION: 'Communication Error',
  },
  DASHBOARD: {
    OVERVIEW_TITLE: 'Dashboard Overview',
    OVERVIEW_SUBTITLE:
      'Monitor platform performance, growth metrics, and recent administrative activities.',
    RECENT_ACTIVITY: 'Recent Activity',
    LATEST_SYSTEM_EVENTS: 'Latest system events',
    VIEW_ALL: 'View all',
    LOADING_ACTIVITIES: 'Loading activities...',
    NO_ACTIVITIES: 'No recent activity detected.',
    SYSTEM_HEALTH: 'System Health',
    REAL_TIME_STATUS: 'Real-time platform status',
    CHECKING_HEALTH: 'Checking health...',
    QUICK_ACTIONS: 'Quick Actions',
    COMMON_ADMIN_TASKS: 'Common administrative tasks',
    STAT_USERS: 'Total Users',
    STAT_UNIVERSITIES: 'Universities',
    STAT_ENTERPRISES: 'Enterprises',
    STAT_INTERNSHIPS: 'Active Internships',
    STAT_STUDENTS: 'Total Students',
    STAT_TERMS: 'Active Terms',
    STAT_PENDING_APPS: 'Pending Apps',
    ERR_STATS_LOAD: 'Failed to load dashboard statistics.',
    ACTION_ADD_UNI: 'Add University',
    ACTION_ADD_ENT: 'Add Enterprise',
    ACTION_MANAGE_USERS: 'Manage Users',
    ACTION_VIEW_REPORTS: 'View Reports',
    DESC_ADD_UNI: 'Register a new partner institution',
    DESC_ADD_ENT: 'Onboard a new corporate partner',
    DESC_MANAGE_USERS: 'View and manage admin accounts',
    DESC_VIEW_REPORTS: 'Platform analytics & statistics',
  },
};
