export const UI_TEXT = {
  COMMON: {
    LOADING: 'Loading...',
    UPLOAD: 'Upload',
    CANCEL: 'Cancel',
    APPLY: 'Apply',
    SAVE: 'Save',
    EDIT: 'Edit',
    DELETE: 'Delete',
    CONFIRM: 'Confirm',
    SUCCESS: 'Success',
    ERROR: 'Error',
    SEARCH: 'Search...',
    FILTER: 'Filter',
    TODAY: 'Today',
    TRY_AGAIN: 'Try Again',
    TOTAL_RECORDS: 'Total records:',
    PAGE: 'page',
    PAGE_SUFFIX: '/page',
    SCORE_DENOMINATOR: '/ 10',
    SLASH: '/',
    ASTERISK: '*',
    DASH: '-',
    OPEN_PAREN: '(',
    CLOSE_PAREN: ')',
    QUESTION: '?',
    UNAUTHORIZED: 'Unauthorized',
    UNAUTHORIZED_DESC: 'You do not have permission to access this page.',
    BACK_TO_LOGIN: 'Back to login',
    NOT_PROVIDED: 'Not provided',
    VAT: 'Tax Code/VAT',
    INFO_ICON: '(i)',
    UNIT_ID_REQUIRED: 'UnitId (required for selected role)',
    UNIT_ID_OPTIONAL: 'UnitId (optional)',
    RETRY: 'Retry',
    MINUS: '-',
    DOUBLE_MINUS: '--',
    TRIPLE_ASTERISK: '***',
    ACTION: 'Action',
    PHASE_VAL: 'phase.',
  },
  USER_MANAGEMENT: {
    TITLE: 'User Management',
    STUDENT_TITLE: 'Student Management',
    STAFF_TITLE: 'Staff Management',
    SUBTITLE: 'Manage accounts and their roles across the hierarchy.',
    CREATE_TITLE: 'Create User',
    EDIT_TITLE: 'Edit User',
    DELETE_TITLE: 'Delete User',
    DELETE_CONFIRM: 'Are you sure you want to delete this user?',
    RESET_PWD_TITLE: 'Reset Password',
    RESET_PWD_CONFIRM: 'Are you sure you want to reset password for this user?',
    ADD: 'Add User',
    CREATE_DESCRIPTION: 'Create a new user account.',
    FULL_NAME: 'Full Name',
    EMAIL_ADDRESS: 'Email Address',
    ASSIGNED_ROLE: 'Assigned Role',
    PHONE_NUMBER: 'Phone Number',
    UNIT: 'Unit',
    CODE: 'Code',
    USER: 'User',
    ROLE: 'Role',
    STATUS: 'Status',
    CREATE_BTN: 'Create',
    CANCEL: 'Cancel',
    NO_DATA: 'No data found',
    SEARCH_PLACEHOLDER: 'Search name/email/code',
    NO: 'No',
    S_FOUND: 's found',
    FILTER_ROLE: 'Filter role',
    FILTER_STATUS: 'Filter status',
    MANAGE_ADMIN_ACCOUNTS: 'Manage accounts across the system',
    DELETE_HINT: 'This action cannot be undone.',
    CONFIRM_DELETE: 'Confirm delete',
    LOSS_ACCESS_HINT: 'User will lose access to the system.',
    RESET_PASSWORD: 'Reset Password',
    ACCOUNT_SECURITY: 'Account Security & Password Reset',
    TARGET: 'Target',
    REASON: 'Reason',
    REASON_PLACEHOLDER: 'Reason (10..500 chars)',
    UPDATE_PROFILE: 'Update Profile',
    UPDATE_INFO: 'Update information for this account.',
    FULL_NAME_LABEL: 'Full name',
    PHONE_OPTIONAL: 'Phone (optional)',
    GENDER: 'Gender',
    MALE: 'Male',
    FEMALE: 'Female',
    OTHER: 'Other',
    DOB_LABEL: 'Date of birth (YYYY-MM-DD)',
    AVATAR_LABEL: 'Avatar URL (optional)',
    CLASS_LABEL: 'Student class (optional)',
    MAJOR_LABEL: 'Student major (optional)',
    GPA_LABEL: 'Student GPA (optional)',
    SAVE_CHANGES: 'Save Changes',
    NOT_FOUND: 'Users not found',
    UNIT_SELECTION_HINT:
      'Unit selection datasource is not available in FE code yet. Enter a UnitId GUID if required.',
    ADMIN_USERS_CAP: 'Users',
    CREATE_CAP: 'Create',
    DELETE_CAP: 'Delete',
    DELETE_BTN: 'Delete',
    FULL_NAME_PLACEHOLDER: 'Enter full name',
    EMAIL_PLACEHOLDER: 'Enter email address',
    PHONE_PLACEHOLDER: 'Enter phone number',
    NO_UNIT_FOUND: 'No unit found',
    SELECT_A: 'Select a',
    S_FOUND_SUFFIX: 's found',
    LOADING_DOTS: 'Loading...',
    ERR_FULL_NAME_REQ: 'Full name is required',
    ERR_EMAIL_REQ: 'Email is required',
    ERR_INVALID_EMAIL: 'Invalid email',
    ERR_CREATE_FAILED: 'Create failed',
    SUCCESS_CREATED: 'Successfully created',
    NOT_MATCHING_CRITERIA: "We couldn't find any users matching your criteria.",
  },
  ENTERPRISES: {
    ONBOARD: 'Onboard Enterprise',
    BRAND_LOGO: 'Brand Logo',
    COVER_IMAGE: 'Cover Image',
    NAME: 'Enterprise Name',
    TAX_ID_LONG: 'Tax Identification Number',
    TAX_ID_SHORT: 'Tax ID',
    INDUSTRY: 'Industry Section',
    DESC: 'Company Description',
    ADDRESS: 'Headquarters Address',
    WEBSITE: 'Corporate Website',
    ENTERPRISE: 'Enterprise',
    INDUSTRY_COLUMN: 'Industry',
  },
  UNIVERSITIES: {
    CREATE: 'Create University',
    NAME: 'University Name',
    CODE: 'University Code',
    ADDRESS: 'Address',
    UNIVERSITY: 'University',
  },
  ENROLLMENT: {
    STUDENT_IN_PHASE: 'This student is currently in the',
    PHASE_HINT:
      'phase. Business details and evaluations will be updated as the internship progresses.',
    IMPORT_TITLE: 'Import Student List',
    IMPORT_SUBTITLE: 'Upload student list to enroll them',
    DOWNLOAD_TEMPLATE: 'Download template',
    DRAG_HINT: 'Drag file here or click to upload (.xls, .xlsx)',
    FILE_SIZE_ERROR: (size) => `File must be < ${size}MB`,
    VALID: 'VALID',
    INVALID: 'INVALID',
    ERROR: 'ERROR',
    TOOLTIP_VALID: 'Valid',
    COLUMNS: {
      FULL_NAME: 'Full Name',
      STUDENT_ID: 'Student ID',
      EMAIL: 'Email',
      VALIDITY: 'Validity',
    },
  },
  USER_PROFILE: {
    VIEW_LINK: 'View Link',
    SKILL_NAME: 'Name',
  },
  BUTTON: {
    CLOSE: 'Close',
    SAVE_CHANGES: 'Save Changes',
    CREATE: 'Create',
    CANCEL: 'Cancel',
    TRY_AGAIN: 'Try Again',
    APPLY: 'Apply',
  },
  TIPTAP: {
    PLACEHOLDER: 'Nhập mô tả...',
    PROMPT_URL: 'Nhập URL',
    IMAGE_ONLY: 'Vui lòng chọn file ảnh',
    IMAGE_TOO_LARGE: 'Ảnh quá lớn. Vui lòng chọn ảnh <= 3MB',
  },
  ROLES: {
    SUPER_ADMIN: 'Super Admin',
    UNI_ADMIN: 'University Admin',
    ORG_ADMIN: 'Organization Admin',
  },
  UPLOADER: {
    EDIT_AVATAR: 'Edit avatar',
    UPDATE_COVER: 'Update Cover Photo',
    UPLOAD_BANNER: 'Upload Cover Banner',
    RATIO_NOTE: 'Recommended ratio 4.5:1',
    LOGO: 'LOGO',
  },
  PAGINATION: {
    TOTAL: 'Total records:',
    PAGE_5: '5/page',
    PAGE_10: '10/page',
    PAGE_20: '20/page',
    PAGE_50: '50/page',
  },
  BACKLOG: {
    INCLUDED_IN_SPRINT: 'will be included in this sprint',
    ISSUE: 'issue',
    ISSUES: 'issues',
    ASTERISK_SPACE: ' *',
    UNKNOWN_EPIC: 'Unknown Epic',
  },
  ENTERPRISE: {
    DASHBOARD_TITLE: 'Enterprise Dashboard',
    DASHBOARD_WELCOME: 'Welcome to the Enterprise Dashboard. Select an option from the sidebar.',
  },
  ERROR: {
    COMMUNICATION: 'Communication Error',
  },
};
