export const UI_TEXT = {
  COMMON: {
    LOADING: 'Loading...',
    UPLOAD: 'Upload',
    CANCEL: 'Cancel',
    APPLY: 'Apply',
    SAVE: 'Save',
    EDIT: 'Edit',
    DELETE: 'Delete',
    CONFIRM: 'Confirm',
    SUCCESS: 'Success',
    ERROR: 'Error',
    SEARCH: 'Search...',
    FILTER: 'Filter',
    TODAY: 'Today',
    TRY_AGAIN: 'Try Again',
    TOTAL_RECORDS: 'Total records:',
    PAGE: 'page',
    PAGE_SUFFIX: '/page',
    SCORE_DENOMINATOR: '/ 10',
    SLASH: '/',
    ASTERISK: '*',
    DASH: '-',
    OPEN_PAREN: '(',
    CLOSE_PAREN: ')',
    QUESTION: '?',
    UNAUTHORIZED: 'Unauthorized',
    UNAUTHORIZED_DESC: 'You do not have permission to access this page.',
    BACK_TO_LOGIN: 'Back to login',
    NOT_PROVIDED: 'Not provided',
    VAT: 'Tax Code/VAT',
    INFO_ICON: '(i)',
    UNIT_ID_REQUIRED: 'UnitId (required for selected role)',
    UNIT_ID_OPTIONAL: 'UnitId (optional)',
    RETRY: 'Retry',
    MINUS: '-',
    ACTION: 'Action',
  },
  ADMIN_USERS: {
    TITLE: 'Admin Users',
    SUBTITLE: 'Manage system administrators and their roles.',
    CREATE_TITLE: 'Create Admin User',
    EDIT_TITLE: 'Edit Admin User',
    DELETE_TITLE: 'Delete Admin User',
    DELETE_CONFIRM: 'Are you sure you want to delete this admin user?',
    RESET_PWD_TITLE: 'Reset Password',
    RESET_PWD_CONFIRM: 'Are you sure you want to reset password for this user?',
    ADD: 'Add Admin User',
    CREATE_DESCRIPTION: 'Create a new admin user account.',
    FULL_NAME: 'Full Name',
    EMAIL_ADDRESS: 'Email Address',
    ASSIGNED_ROLE: 'Assigned Role',
    PHONE_NUMBER: 'Phone Number',
    UNIT: 'Unit',
    CODE: 'Code',
    USER: 'User',
    ROLE: 'Role',
    STATUS: 'Status',
    CREATE_BTN: 'Create',
    CANCEL: 'Cancel',
    NO_DATA: 'No data found',
    SEARCH_PLACEHOLDER: 'Search name/email/code',
    FILTER_ROLE: 'Filter role',
    FILTER_STATUS: 'Filter status',
    MANAGE_ADMIN_ACCOUNTS: 'Manage administrative accounts across the system',
    DELETE_HINT: 'This action cannot be undone.',
    CONFIRM_DELETE: 'Confirm delete',
    LOSS_ACCESS_HINT: 'User will lose access to the system.',
    RESET_PASSWORD: 'Reset Password',
    ACCOUNT_SECURITY: 'Account Security & Password Reset',
    TARGET: 'Target',
    REASON: 'Reason',
    REASON_PLACEHOLDER: 'Reason (10..500 chars)',
    UPDATE_PROFILE: 'Update Profile',
    UPDATE_INFO: 'Update information for this administrative account.',
    FULL_NAME_LABEL: 'Full name',
    PHONE_OPTIONAL: 'Phone (optional)',
    GENDER: 'Gender',
    MALE: 'Male',
    FEMALE: 'Female',
    OTHER: 'Other',
    DOB_LABEL: 'Date of birth (YYYY-MM-DD)',
    AVATAR_LABEL: 'Avatar URL (optional)',
    CLASS_LABEL: 'Student class (optional)',
    MAJOR_LABEL: 'Student major (optional)',
    GPA_LABEL: 'Student GPA (optional)',
    SAVE_CHANGES: 'Save Changes',
    NOT_FOUND: 'Administrators not found',
    UNIT_SELECTION_HINT:
      'Unit selection datasource is not available in FE code yet. Enter a UnitId GUID if required.',
    ADMIN_USERS_CAP: 'Admin users',
    CREATE_CAP: 'Create',
    DELETE_CAP: 'Delete',
    DELETE_BTN: 'Delete',
    FULL_NAME_PLACEHOLDER: 'Full name',
    EMAIL_PLACEHOLDER: 'Email',
    PHONE_PLACEHOLDER: 'Phone number (optional)',
  },
  BUTTON: {
    CLOSE: 'Close',
    SAVE_CHANGES: 'Save Changes',
    CREATE: 'Create',
    CANCEL: 'Cancel',
  },
  TIPTAP: {
    PLACEHOLDER: 'Nhập mô tả...',
    PROMPT_URL: 'Nhập URL',
    IMAGE_ONLY: 'Vui lòng chọn file ảnh',
    IMAGE_TOO_LARGE: 'Ảnh quá lớn. Vui lòng chọn ảnh <= 3MB',
  },
  ROLES: {
    SUPER_ADMIN: 'Super Admin',
    UNI_ADMIN: 'University Admin',
    ORG_ADMIN: 'Organization Admin',
  },
  UPLOADER: {
    EDIT_AVATAR: 'Edit avatar',
    UPDATE_COVER: 'Update Cover Photo',
    UPLOAD_BANNER: 'Upload Cover Banner',
    RATIO_NOTE: 'Recommended ratio 4.5:1',
  },
  PAGINATION: {
    TOTAL: 'Total records:',
    PAGE_5: '5/page',
    PAGE_10: '10/page',
    PAGE_20: '20/page',
    PAGE_50: '50/page',
  },
  BACKLOG: {
    INCLUDED_IN_SPRINT: 'will be included in this sprint',
    ISSUE: 'issue',
    ISSUES: 'issues',
    ASTERISK_SPACE: ' *',
  },
  ENTERPRISE: {
    DASHBOARD_TITLE: 'Enterprise Dashboard',
    DASHBOARD_WELCOME: 'Welcome to the Enterprise Dashboard. Select an option from the sidebar.',
  },
};
