export const COMMON_UI = {
  LABELS: {
    CANCEL: 'Cancel',
    APPLY: 'Apply',
    SAVE: 'Save',
    DELETE: 'Delete',
    EDIT: 'Edit',
    UPLOAD: 'Upload',
    LOADING: 'Loading...',
    TODAY: 'Today',
    ACTION: 'Action',
    SEARCH: 'Search',
    FILTER: 'Filter',
    TOTAL_RECORDS: 'Total records:',
    RECORDS_PER_PAGE: '/page',
    NO_DATA: 'No data found',
    CONFIRM_DELETE: 'Confirm delete',
    BACK_TO_LOGIN: 'Back to login',
    UNAUTHORIZED: 'Unauthorized',
    UNAUTHORIZED_DESC: 'You do not have permission to access this page.',
    CODE: 'Code',
    NAME: 'Name',
    UNIVERSITY: 'University',
    ADDRESS: 'Address',
    USER: 'User',
    UNIT: 'Unit',
    ADMIN_USERS: 'Admin users',
    MANAGE_ADMIN_ACCOUNTS: 'Manage administrative accounts across the system',
    CREATE: 'Create',
    FULL_NAME: 'Full name',
    PHONE_OPTIONAL: 'Phone (optional)',
    GENDER: 'Gender',
    MALE: 'Male',
    FEMALE: 'Female',
    OTHER: 'Other',
    DOB_FORMAT: 'Date of birth (YYYY-MM-DD)',
    AVATAR_URL_OPTIONAL: 'Avatar URL (optional)',
    STUDENT_CLASS_OPTIONAL: 'Student class (optional)',
    STUDENT_MAJOR_OPTIONAL: 'Student major (optional)',
    STUDENT_GPA_OPTIONAL: 'Student GPA (optional)',
    TAX_ID: 'Tax ID',
    ENTERPRISE: 'Enterprise',
    INDUSTRY: 'Industry',
    ONBOARD_ENTERPRISE: 'Onboard Enterprise',
    COMMUNICATION_ERROR: 'Communication Error',
    TRY_AGAIN: 'Try Again',
    ERROR_OCCURRED: 'An error occurred',
    DEFAULT_ERROR_MESSAGE: 'We could not complete your request.',
    VIEW_LINK: 'View Link',
    LOGO: 'LOGO',
    SCORE_DENOMINATOR: '/ 10',
    SCORE_SEPARATOR: '--',
    MASKED_VALUE: '***',
    STUDENT_IN_PHASE: 'This student is currently in the',
    PHASE_DETAILS:
      'phase.\n            Business details and evaluations will be updated as the internship progresses.',
    WILL_BE_IN_SPRINT: 'will be included in this sprint',
    INFO_INDICATOR: '(i)',
  },
  SYMBOLS: {
    ASTERISK: '*',
    HYPHEN: '-',
    ELLIPSIS: '...',
    COLON: ':',
    VERTICAL_DOTS: '⋮',
    CHEVRON_LEFT: '‹',
    CHEVRON_RIGHT: '›',
  },
};
