export const LANDING_UI = {
  NAVBAR: {
    HOME: 'Home',
    DASHBOARD: 'Dashboard',
    LOGOUT: 'Logout',
    LOGIN: 'Login',
  },
  HERO: {
    TITLE: 'Internship OneConnect',
    DESCRIPTION:
      'A comprehensive connection system between Schools, Enterprises, and Students, optimizing the internship management process efficiently and transparently.',
    BUTTON_DASHBOARD: 'Go to Dashboard',
    BUTTON_JOIN: 'Join Now',
  },
  SOLUTIONS: {
    TITLE: 'Comprehensive Solutions',
    DESCRIPTION:
      'Systematize the entire internship process, optimizing time for students, faculty, and businesses.',
    ITEMS: [
      {
        title: 'Smart Allocation',
        desc: 'System automatically suggests internship positions matching student majors and aspirations.',
      },
      {
        title: 'Progress Management',
        desc: 'Track log book, evaluate progress, and approve internship results online.',
      },
      {
        title: '360° Evaluation',
        desc: 'Transparent evaluation process between school and enterprise for each student.',
      },
    ],
  },
  RESERVATION: {
    TITLE_PREFIX: 'Ready to partner with',
    TITLE_HIGHLIGHT: 'Enterprises',
    DESCRIPTION:
      "Leave your information, OneConnect's Partnership team will contact you to consult on the OJT connection process within 24 hours.",
    HOTLINE_LABEL: 'Support Hotline',
    HOTLINE_NUMBER: '1900 1234',
    FORM: {
      PARTNER_INFO_TITLE: 'Partner Information',
      PARTNER_TYPE_UNIVERSITY: 'University / College',
      PARTNER_TYPE_ENTERPRISE: 'Enterprise / Company',
      UNIVERSITY_LABEL: 'University Name',
      ENTERPRISE_LABEL: 'Enterprise Name',
      UNIVERSITY_PLACEHOLDER: 'E.g., ABC University',
      ENTERPRISE_PLACEHOLDER: 'E.g., XYZ Co., Ltd',
      EMAIL: 'Contact Email',
      EMAIL_PLACEHOLDER: 'example@partner.com',
      SEND_OTP: 'Send Code',
      VERIFY_OTP: 'Verify Code',
      OTP_LABEL: 'OTP Code (6 digits)',
      OTP_PLACEHOLDER: '000000',
      OTP_HINT: '* OTP has been sent to your email, valid for 5 minutes.',
      VERIFIED_SUCCESS: 'Email verified. You can now submit.',
      PHONE: 'Contact Phone Number',
      PHONE_PLACEHOLDER: 'E.g., 0987 654 321',
      DATE: 'Preferred Consultation Date',
      TIME_SLOT: 'Preferred Time Slot',
      TIME_PLACEHOLDER: 'Select time slot',
      AREA: 'Cooperation Area',
      AREA_PLACEHOLDER: 'Select area',
      HIRING_COUNT: 'Estimated Scale (Students/Interns)',
      HIRING_PLACEHOLDER: 'E.g., 50',
      NOTE: 'Additional Notes/Requirements',
      NOTE_PLACEHOLDER: 'E.g., We want to connect for the Fall 2024 semester...',
      SUBMIT_BUTTON: 'SEND CONSULTATION REQUEST',
      PROCESSING: 'Processing...',
      SECURITY_NOTICE: 'Your partner information will be kept completely confidential',
      SECURITY_VERIFICATION_TITLE: 'Security Verification',
      SECURITY_VERIFICATION_DESC:
        'We require email verification via OTP to ensure contact accuracy and protect against spam.',
      SELECT_PARTNER_LABEL: 'Select your partner type',
      REGISTRATION_TAG: 'Partner Registration',
      PARTNERS_HIGHLIGHT: 'Partners',
      AREAS: ['Ha Noi', 'Ho Chi Minh City', 'Da Nang', 'Can Thr', 'Other'],
      TIME_SLOTS: ['08:00 - 10:00', '10:00 - 12:00', '13:30 - 15:30', '15:30 - 17:00'],
    },
  },
  FOOTER: {
    DESCRIPTION:
      'Comprehensive Internship Management Platform for universities, enterprises, and students.',
    COLUMNS: {
      SOLUTIONS: 'Solutions',
      NAVIGATION: 'Navigation',
      SUPPORT: 'Support',
    },
    LINKS: {
      SCHOOL: 'For Schools',
      COMPANY: 'For Enterprises',
      HOME: 'Home',
      LOGIN: 'Login',
      HELP_CENTER: 'Help Center',
      SYSTEM_STATUS: 'System Status',
      PRIVACY: 'Privacy Policy',
      TERMS: 'Terms of Service',
    },
    COPYRIGHT: 'All rights reserved.',
    COPYRIGHT_SYMBOL: '©',
    BRAND: 'Internship OneConnect.',
  },
};
