export const ADMIN_DASHBOARD_UI = {
  TITLE: 'ENTERPRISE ADMIN DASHBOARD',
  SUBTITLE: 'Overview of recruitment, internship progress, and violation monitoring.',
  ACCESS_DENIED: 'Access Denied',
  NO_PERMISSION: 'You do not have permission to access the enterprise admin dashboard.',
  SYMBOL_ARROW: '→',
  SYMBOL_CHECK: '✓',
  SYMBOL_BLOCK: '🚫',
  SYMBOL_ALERT: '•',
  SYMBOL_MINUS: '-',
  LABEL_ALL: 'all',
  STATS: {
    INTERN_PHASE_ACTIVE: 'Active Internship Phases',
    PENDING_APPLICATIONS: 'Pending Applications',
    PLACED_STUDENTS: 'Students in Internship',
    ACTIVE_GROUPS: 'Active Internship Groups',
    NEAR_END_PHASES: 'Phases Near Completion',
    UNRESOLVED_VIOLATIONS: 'Unaddressed Violations',
    UNRESOLVED_VIOLATIONS_SUBTITLE: 'Violation reports in the last 30 days',
    REMAINING_CAPACITY: 'Remaining Capacity',
    REMAINING_SLOTS_SUBTITLE: 'Accepting {count} more',
    PENDING_APPS_SUBTITLE: 'Public + Targeted',
    PLACED_STUDENTS_SUBTITLE: 'Self-apply & Uni assign',
    ACTIVE_GROUPS_SUBTITLE: 'In progress',
    NEAR_END_PHASES_BADGE: 'Warning',
    VIOLATION_PREFIX: 'VR',
    REPORTED_BY: 'Reported by',
  },
  PHASES: {
    TITLE: 'Intern Phase Status',
    NAME: 'Phase Name',
    STATUS: 'Status',
    TIMELINE: 'Timeline',
    SLOTS: 'Accepted / Total',
    REMAINING: 'Remaining',
    JOBS: 'Job Postings',
    EMPTY: 'No active internship phases available. Create a new phase to start recruitment.',
    CREATE_NEW: 'Create Intern Phase',
    VIEW_ALL: 'View all phases',
    POSTS: 'Posts',
  },
  GROUPS: {
    TITLE: 'INTERNSHIP GROUPS NEEDING ATTENTION',
    SUBTITLE: 'Groups that have not been assigned a mentor.',
    NAME: 'Group Name',
    PHASE: 'Intern Phase',
    STUDENTS: 'Number of Students',
    START_DATE: 'Start Date',
    ASSIGN_MENTOR: 'Assign Mentor',
    ALL_ASSIGNED: 'No groups found needing mentor assignment.',
    ALL_ASSIGNED_MSG: 'No groups found needing mentor assignment.',
    NO_WARNINGS: 'No warnings',
    VIEW_ALL: 'View All Groups',
    EMPTY: 'No internship groups created yet.',
  },
  VIOLATIONS: {
    TITLE: 'RECENT VIOLATION REPORTS',
    STUDENT: 'Student Name',
    DATE: 'Violation Date',
    GROUP: 'Group Name',
    REPORTER: 'Reported by Mentor',
    CREATED_AT: 'Created At',
    EMPTY: 'No violation reports in the last 30 days.',
    VIEW_ALL: 'View All Violations',
  },
};
