export const ENTERPRISE_DASHBOARD_UI = {
  TITLE: 'Enterprise Dashboard',
  SUBTITLE: 'Welcome back! View your organization summary and recent activities.',
  STATS: {
    TOTAL_INTERNS: 'Total Interns',
    ACTIVE_PROJECTS: 'Active Projects',
    PENDING_APPLICATIONS: 'Pending Applications',
    UPCOMING_INTERVIEWS: 'Upcoming Interviews',
  },
  CHARTS: {
    INTERN_PERFORMANCE: 'Intern Performance Overview',
    APPLICATION_TRENDS: 'Application Trends',
    CHART_PLACEHOLDER: 'Performance charts will be displayed here soon.',
    CONNECTING: 'Connecting to data sources...',
  },
  PHASES_STATUS: {
    TITLE: 'Intern Status by Phases',
    SLOTS: 'Slots',
    EMPTY: 'No internship phases available for this organization.',
  },
  APPLICATIONS: {
    TITLE: 'Applications',
    SELF_APPLY: 'Self-Apply',
    UNI_ASSIGN: 'University-Assigned',
    VIEW_ALL: 'View All Applications',
    NO_CANDIDATES: 'No candidates yet',
    SEPARATOR: '•',
    SV: 'SV',
    PLACED: 'Placed',
    ENROLLMENT_STATUS: 'Enrollment Status',
    ARROW: '→',
  },
  TOTAL: 'Total',
  WELCOME_MESSAGE: 'Welcome to your enterprise workspace',
  LOADING_ANALYZING: 'Analyzing dashboard data...',
  MENTOR: {
    GREETING: 'Hello,',
    WELCOME: 'Welcome back to the Internship Management System.',
    PLACEHOLDER: 'Mentor Dashboard functionality is being updated.',
    EMOJI: '👋',
    EXCLAMATION: '!',
  },
  MENTOR_GROUPS: {
    TITLE: 'Internship Groups Management',
    SUBTITLE: 'Manage and monitor your assigned internship groups.',
    SEARCH_PLACEHOLDER: 'Search by group name or project...',
    ID_PREFIX: 'ID: ',
    EMPTY_STATE: 'No internship groups assigned yet.',
    EMPTY_STATE_DESC: 'Try adjusting your search query or contact your administrator.',
    STUDENTS: 'Students',
    VIEW_DETAILS: 'View Details',
    CHIP_ACTIVE: 'Active',
    CHIP_ARCHIVED: 'Archived',
  },
};
