import { ToastProvider } from '@/providers/ToastProvider';
import './globals.css';

export const metadata = {
  title: 'Internship OneConnect',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/images/logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
