import './globals.css';

import { AntdConfigProvider } from '../providers/AntdConfigProvider';
import { AuthEventsProvider } from '../providers/AuthEventsProvider';
import { PageHeaderProvider } from '../providers/PageHeaderProvider';
import { ReactQueryProvider } from '../providers/ReactQueryProvider';
import { ToastProvider } from '../providers/ToastProvider';

export const metadata = {
  title: 'Internship OneConnect',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/images/logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ReactQueryProvider>
          <PageHeaderProvider>
            <AuthEventsProvider>
              <AntdConfigProvider>
                <ToastProvider>{children}</ToastProvider>
              </AntdConfigProvider>
            </AuthEventsProvider>
          </PageHeaderProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
