import './globals.css';

import { PageHeaderProvider } from '../providers/PageHeaderProvider';
import { ToastProvider } from '../providers/ToastProvider';

export const metadata = {
  title: 'Internship OneConnect',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/images/logo.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PageHeaderProvider>
          <ToastProvider>{children}</ToastProvider>
        </PageHeaderProvider>
      </body>
    </html>
  );
}
