export const STATUS_CONFIG = {
  PENDING: { label: 'Pending', color: 'gold', badge: 'warning' },
  ACCEPTED: { label: 'Accepted', color: 'green', badge: 'success' },
  REJECTED: { label: 'Rejected', color: 'red', badge: 'error' },
  REVOKED: { label: 'Revoked', color: 'default', badge: 'default' },
};

export const MOCK_MENTORS = [
  { id: 'm1', name: 'Sarah Jenkins', role: 'Senior Architect' },
  { id: 'm2', name: 'Marcus Chen', role: 'Lead Developer' },
  { id: 'm3', name: 'Elena Rodriguez', role: 'Product Manager' },
  { id: 'm4', name: 'James Wilson', role: 'Data Scientist' },
];

export const MOCK_GROUPS = [
  {
    id: 'g1',
    name: 'Web Frontend A',
    mentor: 'Sarah Jenkins',
    project: 'E-commerce Platform',
    memberCount: 12,
  },
  {
    id: 'g2',
    name: 'Mobile App Dev B',
    mentor: 'Marcus Chen',
    project: 'Banking App',
    memberCount: 8,
  },
  {
    id: 'g3',
    name: 'Backend Systems C',
    mentor: 'Elena Rodriguez',
    project: 'Logistics System',
    memberCount: 15,
  },
];

export const MOCK_STUDENTS = [
  {
    key: '1',
    id: 1,
    fullName: 'Alex Sterling',
    studentId: 'SV001',
    email: 'alex.s@university.edu',
    major: 'Computer Science',
    status: 'PENDING',
    groupId: null,
    mentorId: null,
    avatar: 'AS',
  },
  {
    key: '2',
    id: 2,
    fullName: 'Marcus Chen',
    studentId: 'SV002',
    email: 'm.chen@statepoly.edu',
    major: 'Software Engineering',
    status: 'ACCEPTED',
    groupId: 'g1',
    mentorId: 'm1',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCaU9FTU6qNRwJ_VLQVNsjlI5KMYyltjw0mXBvLZWYqHyVr2BxhziIC1287YoOGgEywagsmncipmfU-b_OI5eRpAPbZGVRaGa_z1VLq-soJB72FCBahfmoGVYvApM1QaZqOT3xVrNPlKmo1v_wrg1fVm2N7HtLPu8oPaIPpGYTDxNWUnf1DojH1XbCag9L1aTdiTRA2cEKTEoA6ywVo2KFyGJf-8YeON5kLc5nJWg5FhQOF7eWzm9Gl4yP2RUd_fianSgVV2Km7mBM',
  },
  {
    key: '3',
    id: 3,
    fullName: 'Leila White',
    studentId: 'SV003',
    email: 'leila.w@tech.edu',
    major: 'Data Science',
    status: 'REJECTED',
    groupId: null,
    mentorId: null,
    avatar: 'LW',
  },
  {
    key: '4',
    id: 4,
    fullName: 'Elena Rodriguez',
    studentId: 'SV004',
    email: 'e.rodriguez@university.edu',
    major: 'UX Design',
    status: 'ACCEPTED',
    groupId: null,
    mentorId: null,
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBdaJzP8B_D0JFlZJB4MCsxYVIAzXEzq12dTkI-sUSiRH7PPHrcEqEJX5T8ExOMnDbjxYg0nqmllhNtAzHk58sC9sBeQXacBlJ-MKSsVsjOVmVlUXIWMXdOXz-uqFA5wvVoy1w2q83W0Vpv2sCoARFgXGKGNwGxaiU09LOBE5XChr63Bh3KmnsJ9nwMPU4ilUhm3AGS4YW0BIdlESP2uAkQ6TTot1u8D6XLr_RHkPByRrXOo93O_5g94EUkpCbTMbcAeH5C5Gvw32I',
  },
  {
    key: '5',
    id: 5,
    fullName: 'David Park',
    studentId: 'SV005',
    email: 'd.park@uni.edu',
    major: 'Computer Science',
    status: 'PENDING',
    groupId: null,
    mentorId: null,
    avatar: 'DP',
  },
  {
    key: '6',
    id: 6,
    fullName: 'Sophia Lee',
    studentId: 'SV006',
    email: 's.lee@poly.edu',
    major: 'Software Engineering',
    status: 'ACCEPTED',
    groupId: 'g2',
    mentorId: 'm2',
    avatar: 'SL',
  },
  {
    key: '7',
    id: 7,
    fullName: 'Julian Moore',
    studentId: 'SV007',
    email: 'j.moore@col.edu',
    major: 'UX Design',
    status: 'ACCEPTED',
    groupId: 'g3',
    mentorId: 'm3',
    avatar: 'JM',
  },
  {
    key: '8',
    id: 8,
    fullName: 'Maya Patel',
    studentId: 'SV008',
    email: 'm.patel@ist.edu',
    major: 'Data Science',
    status: 'PENDING',
    groupId: null,
    mentorId: null,
    avatar: 'MP',
  },
  {
    key: '9',
    id: 9,
    fullName: 'Lucas Brown',
    studentId: 'SV009',
    email: 'l.brown@univ.edu',
    major: 'Computer Science',
    status: 'REVOKED',
    groupId: null,
    mentorId: null,
    avatar: 'LB',
  },
  {
    key: '10',
    id: 10,
    fullName: 'Emma Wilson',
    studentId: 'SV010',
    email: 'e.wilson@school.edu',
    major: 'Software Engineering',
    status: 'ACCEPTED',
    groupId: 'g1',
    mentorId: 'm1',
    avatar: 'EW',
  },
  {
    key: '11',
    id: 11,
    fullName: 'Noah Garcia',
    studentId: 'SV011',
    email: 'n.garcia@tech.edu',
    major: 'Data Science',
    status: 'PENDING',
    groupId: null,
    mentorId: null,
    avatar: 'NG',
  },
  {
    key: '12',
    id: 12,
    fullName: 'Olivia Taylor',
    studentId: 'SV012',
    email: 'o.taylor@uni.edu',
    major: 'UX Design',
    status: 'REJECTED',
    groupId: null,
    mentorId: null,
    avatar: 'OT',
  },
  {
    key: '13',
    id: 13,
    fullName: 'Ethan Davis',
    studentId: 'SV013',
    email: 'e.davis@poly.edu',
    major: 'Computer Science',
    status: 'ACCEPTED',
    groupId: 'g2',
    mentorId: 'm2',
    avatar: 'ED',
  },
  {
    key: '14',
    id: 14,
    fullName: 'Isabella Hernandez',
    studentId: 'SV014',
    email: 'i.hernandez@col.edu',
    major: 'Software Engineering',
    status: 'PENDING',
    groupId: null,
    mentorId: null,
    avatar: 'IH',
  },
  {
    key: '15',
    id: 15,
    fullName: 'Mason Miller',
    studentId: 'SV015',
    email: 'm.miller@ist.edu',
    major: 'Data Science',
    status: 'ACCEPTED',
    groupId: 'g3',
    mentorId: 'm3',
    avatar: 'MM',
  },
];
