export const PROFILE_UI = {
  PERSONAL_INFO: 'Personal Information',
  AVATAR: {
    TITLE: 'Avatar',
    HINT: 'JPG, PNG format, under 2MB, recommended size: 1200x1200px',
    DEFAULT_NAME: 'User',
  },
  BUTTONS: {
    EDIT: 'Edit',
    UPLOAD_CV: 'Upload CV',
    DONE: 'Done',
    ADD: 'Add',
    CANCEL: 'Cancel',
    SAVE_CHANGES: 'Save Changes',
    DELETE: 'Delete',
  },
  LABELS: {
    FULL_NAME: 'Full Name',
    EMAIL: 'Email',
    PHONE: 'Phone',
    ROLE: 'Role',
    USER_CODE: 'User Code',
    DATE_OF_BIRTH: 'Date of Birth',
    UNIVERSITY: 'University',
    GENDER: 'Gender',
    BIO: 'Bio/About Me',
    EXPERTISE: 'Expertise',
    DEPARTMENT: 'Department',
    POSITION: 'Position',
    PORTFOLIO: 'Portfolio/CV Link',
  },
  SKILLS: {
    TITLE: 'Skills',
    YOUR_SKILLS: 'Your Skills',
    ADD_LABEL: 'Skill',
    LEVEL_LABEL: 'Level',
    PLACEHOLDER: 'e.g. React, Java, SQL',
    LEVEL_PLACEHOLDER: 'Optional',
    MAX_LENGTH_HINT: (current, max) => `(${current}/${max})`,
    LEVELS: [
      { value: 'Beginner', label: 'Beginner' },
      { value: 'Intermediate', label: 'Intermediate' },
      { value: 'Advanced', label: 'Advanced' },
    ],
  },
  CHANGE_PASSWORD: {
    TITLE: 'Change Password',
    HINT: 'Reset your password to protect your account.',
    CURRENT_PASSWORD: 'Current Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    SUBMIT: 'Change Password',
    ERROR: {
      MATCH: 'Passwords do not match',
      FAILED: 'Failed to change password',
      GENERAL: 'An error occurred',
    },
    SUCCESS: 'Password changed successfully',
  },
  LOADING: 'Loading profile...',
  LOADING_ERROR: 'Failed to load profile data',
  UPDATE_SUCCESS: 'Profile updated successfully',
  UPDATE_ERROR: 'Failed to update profile',
  EMPTY: {
    NO_DATA: 'No profile data found.',
  },
};
