export const PROFILE_UI = {
  PERSONAL_INFO: 'Thông tin cá nhân',
  AVATAR: {
    TITLE: 'Ảnh đại diện',
    HINT: 'Định dạng JPG, PNG, kích thước dưới 2MB, Kích thước tiêu chuẩn: 1200x1200px',
    DEFAULT_NAME: 'Người dùng',
  },
  BUTTONS: {
    EDIT: 'Chỉnh sửa thông tin',
    UPLOAD_CV: 'Tải lên CV',
    DONE: 'Xong',
    ADD: 'Thêm',
    CANCEL: 'Hủy',
    SAVE_CHANGES: 'Lưu',
    SAVING: 'Đang lưu...',
    DELETE: 'Xóa',
  },
  CV_HELPER: {
    CURRENT: 'Đã có CV:',
    DOWNLOAD_CURRENT: 'Tải xuống hiện tại',
    DOWNLOAD_CV_ACTION: 'Tải xuống CV',
    READY_TO_UPLOAD: 'Sẵn sàng tải lên:',
    UPLOAD_ERROR: 'Chỉ được tải lên file PDF hoặc Word!',
    SIZE_ERROR: 'File CV phải nhỏ hơn 10MB!',
  },
  VALIDATION: {
    REQUIRED_FULL_NAME: 'Vui lòng nhập họ và tên',
    PHONE_DIGITS: 'Số điện thoại chỉ được chứa chữ số',
    PHONE_MAX: 'Tối đa 15 ký tự',
  },
  PLACEHOLDERS: {
    PHONE: '09xxxxxxxx',
    ADDRESS: 'Số nhà, tên đường, quận/huyện, tỉnh/thành phố',
  },
  LABELS: {
    FULL_NAME: 'Họ và tên',
    EMAIL: 'Email',
    PHONE: 'Số điện thoại',
    ROLE: 'Vai trò',
    USER_CODE: 'Mã số',
    STUDENT_CODE: 'Mã sinh viên',
    DATE_OF_BIRTH: 'Ngày sinh',
    UNIVERSITY: 'Trường học',
    ENTERPRISE: 'Doanh nghiệp',
    GENDER: 'Giới tính',
    BIO: 'Giới thiệu bản thân',
    EXPERTISE: 'Chuyên môn',
    DEPARTMENT: 'Phòng ban/Khoa',
    POSITION: 'Chức vụ',
    PORTFOLIO: 'Portfolio/Link dự án',
    ADDRESS: 'Địa chỉ',
    CV: 'File CV',
    MAJOR: 'Chuyên ngành',
    CLASS: 'Lớp',
    IDENTITY_CARD: 'CCCD/CMND',
    INTERNSHIP_LOCATION: 'Địa điểm thực tập',
  },
  SKILLS: {
    TITLE: 'Skills',
    YOUR_SKILLS: 'Your Skills',
    ADD_LABEL: 'Skill',
    LEVEL_LABEL: 'Level',
    PLACEHOLDER: 'e.g. React, Java, SQL',
    LEVEL_PLACEHOLDER: 'Optional',
    MAX_LENGTH_HINT: (current, max) => `(${current}/${max})`,
    LEVELS: [
      { value: 'Beginner', label: 'Beginner' },
      { value: 'Intermediate', label: 'Intermediate' },
      { value: 'Advanced', label: 'Advanced' },
    ],
  },
  CHANGE_PASSWORD: {
    TITLE: 'Change Password',
    HINT: 'Reset your password to protect your account.',
    CURRENT_PASSWORD: 'Current Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    SUBMIT: 'Change Password',
    ERROR: {
      MATCH: 'Passwords do not match',
      FAILED: 'Failed to change password',
      GENERAL: 'An error occurred',
    },
    SUCCESS: 'Password changed successfully',
  },
  LOADING: 'Loading profile...',
  LOADING_ERROR: 'Failed to load profile data',
  UPDATE_SUCCESS: 'Profile updated successfully',
  UPDATE_ERROR: 'Failed to update profile',
  EMPTY: {
    NO_DATA: 'No profile data found.',
  },
  ROLE_LABELS: {
    1: 'Super Admin',
    2: 'Moderator',
    3: 'Quản trị viên trường',
    4: 'Quản trị viên doanh nghiệp',
    5: 'Nhân sự (HR)',
    6: 'Người hướng dẫn (Mentor)',
    7: 'Sinh viên',
  },
  GENDER_LABELS: {
    1: 'Nam',
    2: 'Nữ',
    3: 'Khác',
    Male: 'Nam',
    Female: 'Nữ',
    Other: 'Khác',
    male: 'Nam',
    female: 'Nữ',
    other: 'Khác',
  },
};
